name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Icons iOS style
  cupertino_icons: ^1.0.8

  # State management (Riverpod)
  flutter_riverpod: ^2.4.0
  
  # State management (Provider) - TAMBAHKAN INI
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true